
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/rust/tags/
image: "rust:latest"

stages:
  - test


# Use cargo clippy and fmt to lint the project
linting:
  stage: test
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo clippy
    - cargo fmt --check

# Use cargo to test the project
testing:
  stage: test
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo test --workspace --verbose

