[package]
name = "drm-gfx"
version = "0.2.0"
edition = "2024"
license = "MIT OR Apache-2.0"
readme = "./README.md"
authors = ["Florian Limburg"]
description = "3D graphics rendering for direct rendering manager with optional tokio thread support"
repository = "https://github.com/FLimburg/drm-gfx"
keywords = ["3dfx", "graphics", "drm"]
autoexamples = true

[lib]
name = "drm_gfx"
path = "src/lib.rs"

[dependencies]
embedded-graphics = { version = "0.8.2" }
embedded-graphics-core = { version = "0.4.0" }
log = "0.4.29"
nalgebra = { version = "0.34.1", default-features = false, features = ["libm"] }
line_drawing = "1.0.1"
drm = "0.14.1"
tokio = { version = "1.49.0", features = ["full"], optional = true }
const_env = "0.1.5"

[features]
tokio-threads = ["tokio"]

[dev-dependencies]
approx = "0.5.1"
