[package]
name = "drm-gfx"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
readme = "./README.md"
description = "3D graphics rendering for direct rendering manager with optional tokio thread support"
repository = "https://gitlab.com/FLimburg/drm-gfx"
keywords = [
    "3dfx",
    "graphics",
    "drm",
]


[dependencies]
embedded-graphics-core = "0.4.0"
log = "0.4.28"
nalgebra = {version = "0.33.2", default-features = false, features = [ "libm" ] }
line_drawing = "1.0.1"
drm = "0.14.1"
tokio = { version = "1.47.1", features = ["full"], optional = true }

[features]
tokio-threads = ["tokio"]

[dev-dependencies]
approx = "0.5.1"
