[package]
name = "drm-gfx"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
readme = "./README.md"
description = "3D graphics rendering for direct rendering manager"
repository = "https://gitlab.com/FLimburg/drm-gfx"
keywords = [
    "3dfx",
    "graphics",
    "drm",
]
repository = "tbd"


[dependencies]
embedded-graphics-core = "0.4.0"
log = "0.4.20"
nalgebra = {version = "0.32.3", default-features = false, features = [ "libm" ] }
line_drawing = "1.0.0"
drm = "0.14.1"
